---
title: "AD698 - Applied Generative AI"
subtitle: "Neural Networks for Classification and Regression"
number-sections: true
date: "2024-11-21"
date-modified: today
date-format: long
engine: jupyter
bibliography: ../references.bib
categories: ['M08:', 'Neural Networks', 'Classification', 'Regression', 'Lecture Notes']
description: "Lecture notes for Module 8 covering Neural Networks for Classification and Regression."
---

# Fine-Tuning, BERT, and Ethical Considerations

The evolution of Transformers led to models like BERT (Bidirectional Encoder Representations from Transformers), which analyze sentences bidirectionally to capture deep semantic and syntactic nuances. While foundation models are versatile, fine-tuning them for specific tasks further enhances their capabilities. *Generative AI Foundations in Python* examines how Parameter-Efficient Fine-Tuning (PEFT) and Low-Rank Adaptation (LoRA) facilitate approachable continued training for specific tasks without the computational overhead of full fine-tuning.

However, deploying these models requires rigorous ethical oversight. Generative models inevitably learn societal biases embedded in the training data and are susceptible to toxicity and accidental memorization of sensitive information. A human-centered AI governance strategy, combining technical improvements, robust guidelines, and ethical reflections, is essential to ensure fairness, accountability, and the responsible adoption of these transformative technologies.


{{< include "./m08_l01_content/1.neural-network-regression.qmd" >}}

<!-- {{< include "./m08_l01_content/1.linear-regression.md" >}}

{{< include "./m08_l01_content/2.oo-design.md" >}}

{{< include "./m08_l01_content/3.synthetic-regression-data.md" >}}

{{< include "./m08_l01_content/4.linear-regression-scratch.md" >}}

{{< include "./m08_l01_content/5.linear-regression-concise.md" >}}

{{< include "./m08_l01_content/6.generalization.md" >}}

{{< include "./m08_l01_content/7.weight-decay.md" >}}


{{< include "./m08_l01_content/8.classification-index.md" >}}
{{< include "./m08_l01_content/9.softmax-regression.md" >}}
{{< include "./m08_l01_content/10.image-classification-dataset.md" >}}
{{< include "./m08_l01_content/11.batch-classification.md" >}}
{{< include "./m08_l01_content/12.softmax-regression-scratch.md" >}}
{{< include "./m08_l01_content/13.softmax-regression-concise.md" >}}
{{< include "./m08_l01_content/14.generalization-classification.md" >}}
{{< include "./m08_l01_content/15.environment-and-distribution-shift.md" >}} -->
